controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


    app_payment:
    path: '/payment'
    controller: 'App\Controller\PaymentController::processPayment'
    methods: ['POST']
